### ISSUE TITLE
Alternate implementation using exiftool

### ISSUE THREAD

**Issue by AlexSzatmary** [BMorearty/exportiphoto#32]
Hi! I appreciate your work on this program. I had trouble getting pyexiv2 to build on my Apple Silicon Mac. I found that exiftool worked great, though, and was able to apply metadata that Photos reads. Because of the scale for this fork, a straight PR might not make sense but you may want to consider linking to my [version](https://github.com/AlexSzatmary/exportiphoto) in your readme.

And thanks, again, for your work on this! I'm able to look at some photos from my adventures from a long time ago and it's been good remembering those times.

-Alex

**Comment by BMorearty** [comment]
Thanks for letting me know, Alex. I've added a link to your fork to the end of my readme.

**Comment by AlexSzatmary** [comment]
Awesome, thanks!
